# Generated by Django 5.1.5 on 2026-03-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EconomistArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('section', models.CharField(blank=True, max_length=200, verbose_name='栏目分类')),
                ('snippet', models.TextField(blank=True, verbose_name='摘要')),
                ('link', models.TextField(verbose_name='原文链接')),
                ('link_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='链接哈希')),
                ('content', models.TextField(blank=True, verbose_name='正文（前两段合并）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='导入时间')),
            ],
            options={
                'verbose_name': '经济学人文章',
                'verbose_name_plural': '经济学人文章',
                'ordering': ['-id'],
            },
        ),
    ]
