# Generated by Django 5.2.9 on 2026-01-01 17:31

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='药品通用名')),
                ('category', models.CharField(choices=[('感冒', '感冒类'), ('消炎', '消炎类'), ('慢性病', '慢性病'), ('儿童', '儿童用药')], max_length=50, verbose_name='分类')),
                ('barcode', models.CharField(max_length=50, unique=True, verbose_name='条形码/国药准字')),
                ('description', models.TextField(blank=True, verbose_name='说明书/功效')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
            ],
            options={
                'verbose_name': '全局标准药库',
                'verbose_name_plural': '全局标准药库',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('user', '普通家庭用户'), ('admin_user', '用户管理员'), ('admin_med', '药品管理员'), ('admin_post', '帖子管理员'), ('admin_sys', '系统管理员')], default='user', max_length=20, verbose_name='角色身份')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='手机号')),
                ('family_id', models.CharField(blank=True, help_text='同一ID视为一家人', max_length=20, null=True, verbose_name='家庭组ID')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='药品名称')),
                ('production_date', models.DateField(verbose_name='生产日期')),
                ('expiration_date', models.DateField(verbose_name='过期日期')),
                ('stock', models.IntegerField(verbose_name='剩余数量')),
                ('unit', models.CharField(default='盒', max_length=10, verbose_name='单位')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='归属人')),
                ('global_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.globalmedicine', verbose_name='关联标准库')),
            ],
            options={
                'verbose_name': '我的家庭药箱',
                'verbose_name_plural': '我的家庭药箱',
            },
        ),
        migrations.CreateModel(
            name='SharePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(verbose_name='描述信息')),
                ('status', models.IntegerField(choices=[(0, '待审核'), (1, '审核通过'), (2, '驳回/违规')], default=0, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.familymedicine', verbose_name='转让药品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
            ],
            options={
                'verbose_name': '药品共享广场',
                'verbose_name_plural': '药品共享广场',
            },
        ),
    ]
