# Generated by Django 5.2.9 on 2026-02-15 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300, verbose_name='留言内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='留言时间')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sharepost', verbose_name='帖子')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='留言人')),
            ],
            options={
                'verbose_name': '帖子留言',
                'verbose_name_plural': '帖子留言',
            },
        ),
    ]
