# Generated by Django 5.2.9 on 2026-02-23 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_add_post_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='read_at',
            field=models.DateTimeField(blank=True, help_text='为空表示帖子主人未读', null=True, verbose_name='帖子主人阅读时间'),
        ),
    ]
