# Generated by Django 5.2.9 on 2026-02-23 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_add_comment_read_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300, verbose_name='回复内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='回复时间')),
                ('read_at', models.DateTimeField(blank=True, help_text='为空表示被回复的留言人未读', null=True, verbose_name='留言人阅读时间')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.postcomment', verbose_name='针对的留言')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='回复人（通常为帖子主人）')),
            ],
            options={
                'verbose_name': '留言回复',
                'verbose_name_plural': '留言回复',
            },
        ),
    ]
