# Generated by Django 5.2.9 on 2026-03-02 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_add_comment_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='公告标题')),
                ('content', models.TextField(verbose_name='公告内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
            ],
            options={
                'verbose_name': '系统公告',
                'verbose_name_plural': '系统公告',
                'ordering': ['-is_pinned', '-create_time'],
            },
        ),
    ]
