# Generated by Django 5.2.9 on 2026-03-03 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_add_system_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymedicine',
            name='audit_status',
            field=models.IntegerField(choices=[(0, '待审核'), (1, '审核通过'), (2, '审核驳回')], default=1, verbose_name='审核状态'),
        ),
        migrations.AddField(
            model_name='familymedicine',
            name='auditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_family_medicines', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.CreateModel(
            name='FamilyJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_family_id', models.CharField(max_length=20, verbose_name='目标家庭组ID')),
                ('status', models.IntegerField(choices=[(0, '待审核'), (1, '审核通过'), (2, '审核驳回')], default=0, verbose_name='审核状态')),
                ('review_note', models.CharField(blank=True, max_length=200, verbose_name='审核备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('review_time', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_join_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_family_join_requests', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '家庭组加入申请',
                'verbose_name_plural': '家庭组加入申请',
                'ordering': ['-create_time'],
            },
        ),
    ]
