# Generated by Django 5.2.9 on 2026-03-03 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_familymedicine_audit_status_familymedicine_auditor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500, verbose_name='消息内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='已读时间')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_private_messages', to=settings.AUTH_USER_MODEL, verbose_name='接收方')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_private_messages', to=settings.AUTH_USER_MODEL, verbose_name='发送方')),
            ],
            options={
                'verbose_name': '私聊消息',
                'verbose_name_plural': '私聊消息',
                'ordering': ['create_time'],
            },
        ),
    ]
