# Generated by Django 5.2.9 on 2026-03-03 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_privatemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymedicine',
            name='daily_reminder_time',
            field=models.TimeField(blank=True, null=True, verbose_name='每日提醒时间'),
        ),
        migrations.AddField(
            model_name='familymedicine',
            name='dosage_note',
            field=models.CharField(blank=True, max_length=100, verbose_name='用药提示'),
        ),
        migrations.AddField(
            model_name='familymedicine',
            name='reminder_enabled',
            field=models.BooleanField(default=False, verbose_name='启用服药提醒'),
        ),
        migrations.AddField(
            model_name='sharepost',
            name='medicine_audit_status',
            field=models.IntegerField(choices=[(0, '待审核'), (1, '审核通过'), (2, '审核驳回')], default=0, verbose_name='药品审核状态'),
        ),
        migrations.AddField(
            model_name='sharepost',
            name='medicine_audit_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='药品审核时间'),
        ),
        migrations.AddField(
            model_name='sharepost',
            name='medicine_auditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_share_post_medicines', to=settings.AUTH_USER_MODEL, verbose_name='药品审核人'),
        ),
        migrations.CreateModel(
            name='MedicalTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('tip_date', models.DateField(unique=True, verbose_name='发布日期')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_medical_tips', to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
            ],
            options={
                'verbose_name': '医学小贴士',
                'verbose_name_plural': '医学小贴士',
                'ordering': ['-tip_date', '-create_time'],
            },
        ),
        migrations.CreateModel(
            name='SharePostMedicineAdoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adopted_post_medicines', to=settings.AUTH_USER_MODEL, verbose_name='接收用户')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoptions', to='app.sharepost', verbose_name='来源帖子')),
            ],
            options={
                'verbose_name': '帖子药品加入记录',
                'verbose_name_plural': '帖子药品加入记录',
                'unique_together': {('post', 'adopter')},
            },
        ),
    ]
