# Generated by Django 5.2.9 on 2026-03-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_familymedicine_daily_reminder_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharepost',
            name='medicine_audit_status',
            field=models.IntegerField(choices=[(-1, '待帖子审核'), (0, '待药品审核'), (1, '审核通过'), (2, '审核驳回')], default=-1, verbose_name='药品审核状态'),
        ),
    ]
